language: python

sudo: false

python:
  - 3.6
  - 3.7

install:
  - pip install numpy
  - pip install scipy
  - pip install dask
  - pip install xarray
  - pip install pandas
  - pip install numba
  - pip install netcdf4
  - pip install codecov

script:
  - cd global_forecast_validation/tests
  - coverage run tests.py

after_success:
  - codecov
