language: python

sudo: false

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install numpy
  - pip install scipy
  - pip install dask[complete]
  - pip install xarray
  - pip install pandas
  - pip install numba
  - pip install netcdf4
  - pip install progress
  - pip install codecov

script:
  - cd global_forecast_validation/tests
  - coverage run tests.py

after_success:
  - codecov
